concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docweb"
  url = "https://git.fhict.nl/"
  id = 10115
  token = "glrt-AGTS3Qm71m8AkoMG_5bF"
  token_obtained_at = 2024-09-16T13:00:31Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "drawling"
  url = "https://git.fhict.nl/"
  id = 10243
  token = "glrt-fjydY47UjHLrAsDvsP_z"
  token_obtained_at = 2024-09-20T21:22:22Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
